# Generated by Django 5.0.6 on 2024-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Santechapp', '0002_auto_20200715_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='prescription',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
