# Generated by Django 5.0.6 on 2024-07-07 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Santechapp', '0006_rename_tva_medicine_tva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybank',
            name='ifsc_no',
        ),
    ]
